// Audits the ported elements against what defends them: a widget the element
// maps to, a test that names it, and a place it is reachable from. Writes
// doc/element-audit.md. Mechanical only — it reports where to look, not whether
// the look is right.
//
//   dart run tool/audit_elements.dart

import 'dart:io';

/// One row of `doc/element-coverage.md`.
class _Row {
  _Row(this.element, this.status, this.path);

  final String element;
  final String status;
  final String? path;
}

void main() {
  final File coverage = File('doc/element-coverage.md');
  if (!coverage.existsSync()) {
    stderr.writeln('doc/element-coverage.md is missing; run sync_element_coverage first.');
    exit(1);
  }

  final List<_Row> rows = <_Row>[];
  for (final String line in coverage.readAsLinesSync()) {
    final RegExpMatch? match = RegExp(r'^\| `([^`]+)` \| (\w+) \| [^|]+ \| ([^|]+) \|')
        .firstMatch(line);
    if (match == null) continue;
    final String file = match.group(3)!.trim();
    rows.add(_Row(
      match.group(1)!,
      match.group(2)!,
      file == '—' ? null : file.replaceAll('`', '').trim(),
    ));
  }

  final String tests = _readAll(Directory('test'));
  final String gallery = _readAll(Directory('landing/lib'))
      + _readAll(Directory('example/lib'));
  final String publicApi = File('lib/assistant_ui.dart').readAsStringSync();

  final List<String> noWidget = <String>[];
  final List<String> noTest = <String>[];
  final List<String> noSurface = <String>[];
  int checked = 0;

  for (final _Row row in rows) {
    if (row.status != 'ported' && row.status != 'partial') continue;
    checked++;
    final String? path = row.path;
    if (path == null) {
      noWidget.add(row.element);
      continue;
    }
    // A row may name several files, and a helper may live beside the element
    // rather than in the file the row names; read all of them.
    final List<String> sources = <String>[
      for (final String part in path.split(',')) File('lib/src/${part.trim()}').path,
    ].where((String p) => File(p).existsSync()).toList();
    final String source = sources.isEmpty
        ? _sourceDeclaring(row.element)
        : sources.map((String p) => File(p).readAsStringSync()).join('\n');
    // The classes the element's file exports, as the tests and the surfaces
    // would name them.
    final List<String> classes = RegExp(r'^class (\w+)', multiLine: true)
        .allMatches(source)
        .map((RegExpMatch m) => m.group(1)!)
        .where((String name) => publicApi.contains(name))
        .toList();
    if (classes.isEmpty) {
      noWidget.add(row.element);
      continue;
    }
    if (!classes.any(tests.contains)) noTest.add(row.element);
    // Reachable surfaces: a gallery page, an example, or the landing.
    final String tokens = row.element.replaceAll('-', '');
    final bool listed = gallery.contains(row.element) ||
        gallery.contains(tokens) ||
        classes.any(gallery.contains);
    if (!listed) noSurface.add(row.element);
  }

  final StringBuffer out = StringBuffer()
    ..writeln('# Element audit')
    ..writeln()
    ..writeln('Generated by `dart run tool/audit_elements.dart` — do not edit by hand.')
    ..writeln()
    ..writeln('Mechanical pass over the ported elements: does the element map to a file '
        'that exports a public class, does a test name that class, and is it '
        'reachable from the gallery, the example or the landing. It says where to '
        'look; it does not judge the design.')
    ..writeln()
    ..writeln('| | Count |')
    ..writeln('|---|---|')
    ..writeln('| ported or partial elements checked | $checked |')
    ..writeln('| file missing or exports nothing public | ${noWidget.length} |')
    ..writeln('| no test names the element\'s class | ${noTest.length} |')
    ..writeln('| not reachable from a surface | ${noSurface.length} |')
    ..writeln();

  void section(String title, List<String> items, String meaning) {
    out
      ..writeln('## $title')
      ..writeln()
      ..writeln(meaning)
      ..writeln();
    if (items.isEmpty) {
      out.writeln('None.');
    } else {
      for (final String item in items..sort()) {
        out.writeln('- `$item`');
      }
    }
    out.writeln();
  }

  section(
    'No widget',
    noWidget,
    'The coverage table points at a file that is missing or exports no public class.',
  );
  section(
    'No test',
    noTest,
    'No test file names the element\'s class. The element may still be covered '
    'through a shared test; these are the ones to check by hand.',
  );
  section(
    'No surface',
    noSurface,
    'Nothing in the gallery, the example or the landing renders the element, so a '
    'reader cannot see it running.',
  );

  File('doc/element-audit.md').writeAsStringSync(out.toString());
  stdout.writeln('wrote doc/element-audit.md: $checked elements, '
      '${noWidget.length} without a widget, ${noTest.length} without a test, '
      '${noSurface.length} without a surface');
}

/// Last resort: the file under `lib/src` that declares a class named after the
/// element, so a stale path in the coverage table does not read as a missing
/// widget.
String _sourceDeclaring(String element) {
  final String needle = element
      .split('-')
      .map((String part) =>
          part.isEmpty ? part : part[0].toUpperCase() + part.substring(1))
      .join();
  for (final FileSystemEntity entity
      in Directory('lib/src').listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final String text = entity.readAsStringSync();
    if (text.contains('class Assistant$needle') ||
        text.contains('class Aui$needle')) {
      return text;
    }
  }
  return '';
}

String _readAll(Directory dir) {
  if (!dir.existsSync()) return '';
  final StringBuffer buffer = StringBuffer();
  for (final FileSystemEntity entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      buffer.writeln(entity.readAsStringSync());
    }
  }
  return buffer.toString();
}
